spring:
  datasource:
#    url: jdbc:h2:~/spring-batch
    url: jdbc:h2:tcp://localhost/~//spring-batch
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  batch:
    jdbc:
      initialize-schema: always