spring:
  datasource:
    meta:
      jdbc-url: jdbc:mysql://localhost:3306/meta_db?serverTimezone=Asia/Seoul
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:~/spring-batch
#    url: jdbc:h2:tcp://localhost/~//spring-batch
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    data:
      jdbc-url: jdbc:mysql://localhost:3306/data_db?serverTimezone=Asia/Seoul
      username: root
      password: 12345678
      driver-class-name: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
mybatis:
  mapper-locations: classpath:mapper/*.xml