spring:
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:~/spring-batch
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    job:
      enabled: false
